title: "DexNeXuS Streamer.bot Extensions"
description: "Custom Streamer.bot Extensions, Twitch Overlays & OBS Widgets"
url: "https://dexnexus.github.io"
baseurl: "/Streamer.Bot"
author: "DexNeXuS"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
sitemap:
  filename: "sitemap.xml"
  exclude:
    - /assets/
    - /404.html
